<a href="https://colab.research.google.com/github/venkatesh1992/Practise/blob/mybranch/pandas_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/nyc_weather.csv')

In [ ]:
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [ ]:
df['Temperature'].max()

50

In [ ]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [ ]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [ ]:
df['EST'][df['Events']=='Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [ ]:
df = pd.read_csv('weather_data.csv')

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

we can create dataframe by using list and dictionary as well

In [ ]:
weather_data={
    'day':['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature':[32,35,28,24,32,31],
    'windspeed':[6,7,2,7,4,2],
    'event':['Rain','Sunny','Snow','Snow','Rain','Sunny']
}
df=pd.DataFrame(weather_data)

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.shape

(6, 4)

In [ ]:
#shape will give number of records and columns in a tuple
rows,columns = df.shape

In [ ]:
rows

6

In [ ]:
columns

4

In [ ]:
#head will give first 5 rows
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [ ]:
#tail will give last 5 rows
df.tail(1)

        day  temperature  windspeed  event
5  1/6/2017           31          2  Sunny

In [ ]:
# we can number as well, how many records we want
df.head(2)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [ ]:
# we can get records based on index and slicing as well
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [ ]:
#to get columns we will use columns method
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
#df.event
#or (both will work fine)
df['event']

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [ ]:
df[['day','temperature']]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(df.event)

pandas.core.series.Series

In [ ]:
df['temperature'].max()

35

In [ ]:
df['temperature'].min()

24

In [ ]:
df['temperature'].median()

31.5

In [ ]:
df['temperature'].std()

3.8297084310253524

In [ ]:
df['temperature'].mode()

0    32
Name: temperature, dtype: int64

In [ ]:
# describe will give stats of all the integer columns
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [ ]:
#how to select data based on condition
df['day'][df['temperature']>28]

0    1/1/2017
1    1/2/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.set_index('day')

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
#when you set index it will create a new dataframe,it won't change the existing one
#if we want to change existing one, we need to add inplace=True
df.set_index('day',inplace=True)

In [ ]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [ ]:
# to reset the index we can use reset_index
df.reset_index()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

## different ways of creating dataframe in pandas


1.   by using read files **pd.read_csv('filepath')**
2.   by using read_excel **pd.read_excel('filepath',sheetname)**
3.   by using **pd.DataFrame(python dictionary)**
4.   by using **pd.DataFrame(list of tuples,column names)**
5.   by using **pd.DataFrame(list of dictionaries)**

In [ ]:
#by using read files pd.read_csv('filepath')
df_csv=pd.read_csv('weather_data.csv')

In [ ]:
df_csv

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
#2.   by using read_excel **pd.read_excel('filepath',sheetname)**
df_excel = pd.read_excel('weather_data.xlsx','Sheet1')

In [ ]:
df_excel

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [ ]:
#3.   by using **pd.DataFrame(python dictionary)**
weather_data={
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature':[32,35,28],
    'windspeed':[6,7,2],
    'event':['Rain','Sunny','Snow']
}
df_dict = pd.DataFrame(weather_data)
df_dict

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [ ]:
#4.   by using **pd.DataFrame(list of tuples,column names)**
weather_data_list=[
    ('1/1/2017',32,6,'Rainy'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df_list = pd.DataFrame(weather_data_list,columns=["day","temperature","windspeed","event"])
df_list

        day  temperature  windspeed  event
0  1/1/2017           32          6  Rainy
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [ ]:
#5.   by using **pd.DataFrame(list of dictionaries)**
weather_data_list_dict=[
    {'day':'1/1/2017','temperature':32,'windspeed':6,'event':'Rainy'},
    {'day':'1/2/2017','temperature':35,'windspeed':7,'event':'Sunny'},
    {'day':'1/3/2017','temperature':28,'windspeed':2,'event':'Snow'}
]
df_list_dict = pd.DataFrame(weather_data_list_dict)
df_list_dict

        day  temperature  windspeed  event
0  1/1/2017           32          6  Rainy
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

## Read and write CSV and Excel

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('stock_data.csv')

In [ ]:
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
#what if my file has extra header
df = pd.read_csv('stock_data.csv')

In [ ]:
df

                                            Stocks
tickers eps           revenue price         people
GOOGL   27.82         87      845       larry page
WMT     4.61          484     65              n.a.
MSFT    -1            85      64        bill gates
RIL     not available 50      1023   mukesh ambani
TATA    5.6           -1      n.a.      ratan tata

In [ ]:
df = pd.read_csv('stock_data.csv',header=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv('stock_data.csv',skiprows=1)
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
#what if my file doesn't have header
df = pd.read_csv('stock_data.csv')
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [ ]:
#what if my file doesn't have header
df = pd.read_csv('stock_data.csv',header=None)
df

       0              1    2     3              4
0  GOOGL          27.82   87   845     larry page
1    WMT           4.61  484    65           n.a.
2   MSFT             -1   85    64     bill gates
3   RIL   not available   50  1023  mukesh ambani
4   TATA            5.6   -1  n.a.     ratan tata

In [ ]:
#if there is no header we can pass column names while reading
df = pd.read_csv('stock_data.csv',names=['tickers','eps','revenue','price','people'])
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
#my csv file is too big,i want to read few rows only(we can mention while reading itself)
df = pd.read_csv('stock_data.csv',nrows=3)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

In [ ]:
#my csv has 100 columns,i want to read 2 columns only(we can mention while reading itself)
df = pd.read_csv('stock_data.csv',usecols=['tickers','eps'])
df

  tickers            eps
0   GOOGL          27.82
1     WMT           4.61
2    MSFT             -1
3    RIL   not available
4    TATA            5.6

In [ ]:
#filling na vlaues while reading file
df = pd.read_csv('stock_data.csv',na_values=['n.a.','not available'])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [ ]:
#what if i we want make nagative values to 0 or NaN
df = pd.read_csv('stock_data.csv',na_values=['n.a.','not available',-1])
df
#here it is converting eps value also to Nan, we don't want that

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [ ]:
df = pd.read_csv('stock_data.csv',na_values=
 {'revenue':['n.a.','not available',-1],
  'price':['n.a.','not available',-1],
  'people':['n.a.','not available',-1],
  'eps':['n.a.','not available']})
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT  -1.00     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [ ]:
#now we will see writing to csv file
# we have to_csv nmethod
df.to_csv('new.csv')

In [ ]:
#above method wrote index also to file, we don't want index then we can make index=flase
df.to_csv('new.csv',index=False)

In [ ]:
#what if i want to write few colums only
df.to_csv('new.csv',index=False,columns=['tickers','eps'])

In [ ]:
#what if i don't want header while writing
df.to_csv('new.csv',index=False,header=None)

In [ ]:
#what if i don't want header while writing
df.to_csv('new.csv',index=False,header=False)

In [ ]:
#now we will see reading excel file
df = pd.read_excel('stock_data.xlsx','Sheet1')
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
#while reading excel file we have additional methods like converters to clean the messsy data
def convert_people_cell(cell):
  if cell == 'n.a.':
    return 'sam walton'
  return cell

# converters will take method in dictionary
df = pd.read_excel('stock_data.xlsx','Sheet1',converters={
    'people':convert_people_cell
})
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65     sam walton
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
#similarly if i want to convert other cells,we can add additional methods
def convert_people_cell(cell):
  if cell == 'n.a.':
    return 'sam walton'
  return cell

def convert_eps_cell(cell):
  if cell == 'not available':
    return None
  return cell

# converters will take method in dictionary
df = pd.read_excel('stock_data.xlsx','Sheet1',converters={
    'people':convert_people_cell,
    'eps':convert_eps_cell
})
df

  tickers    eps  revenue price         people
0   GOOGL  27.82       87   845     larry page
1     WMT   4.61      484    65     sam walton
2    MSFT  -1.00       85    64     bill gates
3    RIL     NaN       50  1023  mukesh ambani
4    TATA   5.60       -1  n.a.     ratan tata

In [ ]:
#now we will see writing
df.to_excel("new.xlsx",sheet_name='stocks')

In [ ]:
#in excel , writing we can mention start row and start column(so that it will write from that point)
df.to_excel("new.xlsx",sheet_name='stocks',index=False,startrow=2,startcol=2)

In [ ]:
import pandas as pd

In [ ]:
#suppose if i have two dataframes, iwant to write to single excel with different sheets we have ExcelWriter class in pandas
df_weather = pd.DataFrame(
    {
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature':[32,35,28],
    'windspeed':[6,7,2],
    'event':['Rain','Sunny','Snow']
}
)
df_weather

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [ ]:
df_stocks = pd.DataFrame(
    {
    'tickers': ['GOOGL','WMT','MST'],
    'price':[32,35,28],
    'pe':[6,7,2],
    'eps':[1,2,3]
}
)
df_stocks

  tickers  price  pe  eps
0   GOOGL     32   6    1
1     WMT     35   7    2
2     MST     28   2    3

In [ ]:
with pd.ExcelWriter('weather_stocks.xlsx') as writer:
  df_stocks.to_excel(writer,'stocks')
  df_weather.to_excel(writer,'weather')

**Handling missing Data**


1.   fillna
2.   interpolate
3.   dropna

In [ ]:
import pandas as pd
df = pd.read_csv('weather_data.csv')
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [ ]:
#i want to covert my date columns to date then
df = pd.read_csv('weather_data.csv',parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
# now i want to make day as index
df.set_index('day',inplace=True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
# i want fill na with 0
df.fillna(0)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
#it is filling event also to 0, it looks weird to overcome that we will fill column wise
df.fillna({
    'temperature':0,
    'windspeed':0,
    'event':'No forecast'
})

            temperature  windspeed        event
day
2017-01-01         32.0        6.0         Rain
2017-01-04          0.0        9.0        Sunny
2017-01-05         28.0        0.0         Snow
2017-01-06          0.0        7.0  No forecast
2017-01-07         32.0        0.0         Rain
2017-01-08          0.0        0.0        Sunny
2017-01-09          0.0        0.0  No forecast
2017-01-10         34.0        8.0       Cloudy
2017-01-11         40.0       12.0        Sunny

In [ ]:
#instaed of making it to 0, we will fill that with previuos or after not null value, for better estimates
#for mean and average calculations
df.fillna(method='ffill') # previous data not null value

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
df.fillna(method='bfill') # next day value

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
# by using method='ffill'/bfill it is copying data vertically
# if i want my data to be copied horizontally then use axis and mention columns
df.fillna(method='bfill',axis='columns')

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

In [ ]:
df.fillna(method='ffill',axis='columns')

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         NaN       9.0   Sunny
2017-01-05        28.0      28.0    Snow
2017-01-06         NaN       7.0     7.0
2017-01-07        32.0      32.0    Rain
2017-01-08         NaN       NaN   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

In [ ]:
#suppose i want to carry forward my value to next record only then we will use limit
df
df.fillna(method='ffill',limit=1)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
df.fillna(method='ffill',limit=2)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
#still the tempearture is not better estimate, to do that we have interpolate method in pandas
df.interpolate()

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    30.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [ ]:
#by default interpolate will do linaer guess, we can pass time as well
df.interpolate(method='time')

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [ ]:
# if i want to drop null values we have dropna method
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
df.dropna()
# by default it will drop the full record, it it is having atleast one null value

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
#if i want delete only all the values are null
df.dropna(how='all')

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
# suppose i want to delete based on thresold of null values
# assume i want to drop record, if it has atleast two null values then we need to mention thresh=2
df.dropna(thresh=1) # it will drop it all the cols are null

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
df.dropna(thresh=2)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-07         32.0        NaN    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
# how to fill data ranges
dt = pd.date_range("01-01-2017","01-11-2017")
idx= pd.DatetimeIndex(dt)
new_df=df.reindex(dt)

In [ ]:
new_df

            temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
new_df.interpolate(method='time')

            temperature  windspeed   event
2017-01-01    32.000000       6.00    Rain
2017-01-02    31.000000       7.00     NaN
2017-01-03    30.000000       8.00     NaN
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

**Replace**

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [ ]:
df.replace(-99999,np.NaN)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [ ]:
#what if my data has mutiple values to replcae like -9999 and -8888, how to provide multiple values
# we can provide in list
df = pd.read_csv('weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28      -8888   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [ ]:
df.replace([-99999,-8888],np.NAN)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [ ]:
#still event has 0 value which is not correct,
#if i pass Zero in list and it will replace 0 in all the int columns which is not expected
df.replace([-99999,-8888,'0'],np.NAN)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [ ]:
#to overcome above we can pass columns and replace values in dictionary
df.replace({
    'temperature':[-99999,-8888],
    'windspeed':[-99999,-8888],
    'event':'0'
},np.NaN)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [ ]:
#what if my data has unit of measures also like 32F,12C,12mph like
# to replace those we need to use regex
df = pd.read_csv('weather_data.csv')
df

          day temperature windspeed  event
0  01-01-2017         32F         6   Rain
1  01-02-2017      -99999     7 mph  Sunny
2  01-03-2017          28     -8888   Snow
3  01-04-2017      -99999         7      0
4  01-05-2017         32C    -99999   Rain
5  01-06-2017          31    2 kmph  Sunny
6  01-06-2017          34         5      0

In [ ]:
df.replace('[a-zA-Z]','') # it didn't repalce, we need to mention regex=True

          day temperature windspeed  event
0  01-01-2017         32F         6   Rain
1  01-02-2017      -99999     7 mph  Sunny
2  01-03-2017          28     -8888   Snow
3  01-04-2017      -99999         7      0
4  01-05-2017         32C    -99999   Rain
5  01-06-2017          31    2 kmph  Sunny
6  01-06-2017          34         5      0

In [ ]:
df.replace('[a-zA-Z]','',regex=True)
#the problem is it replaces values in event also, which is not expected

          day temperature windspeed event
0  01-01-2017          32         6
1  01-02-2017      -99999        7
2  01-03-2017          28     -8888
3  01-04-2017      -99999         7     0
4  01-05-2017          32    -99999
5  01-06-2017          31        2
6  01-06-2017          34         5     0

In [ ]:
#to overcome we will pass regex with columns
df.replace({
    'temperature':'[a-zA-Z]',
    'windspeed':'[a-zA-Z]'
},'',regex=True)

          day temperature windspeed  event
0  01-01-2017          32         6   Rain
1  01-02-2017      -99999        7   Sunny
2  01-03-2017          28     -8888   Snow
3  01-04-2017      -99999         7      0
4  01-05-2017          32    -99999   Rain
5  01-06-2017          31        2   Sunny
6  01-06-2017          34         5      0

In [ ]:
#now I have a list of values,now i want to replace all values with other values
# to do this we will pass 2 list, one with old values and one with new values
df = pd.DataFrame({
    'score':['exceptional','average','good','poor','average','exceptional'],
    'student':['rob','maya','venki','raju','ram','tom']
})
df

         score student
0  exceptional     rob
1      average    maya
2         good   venki
3         poor    raju
4      average     ram
5  exceptional     tom

In [ ]:
#in scores instead of strings, i want integer values like 1 to 5
#exceptional:5,good:4,average:3,poor:2
df.replace(['exceptional','good','average','poor'],[5,4,3,2])

   score student
0      5     rob
1      3    maya
2      4   venki
3      2    raju
4      3     ram
5      5     tom

In [ ]:
df = pd.read_csv('weather_by_cities.csv')
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [ ]:
g=df.groupby('city')
g

In [ ]:
for city,city_df in g:
  print(city)
  print(city_df)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [ ]:
g.get_group('mumbai')

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

In [ ]:
g.min()

               day  temperature  windspeed   event
city
mumbai    1/1/2017           85          5     Fog
new york  1/1/2017           28          6    Rain
paris     1/1/2017           42          8  Cloudy

In [ ]:
g.min('windspped')

          temperature  windspeed
city
mumbai             85          5
new york           28          6
paris              42          8

In [ ]:
g.max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [ ]:
g.max('windspeed')

          temperature  windspeed
city
mumbai             92         15
new york           36         12
paris              54         20

In [ ]:
g.mean()

<ipython-input-64-c79523bc0c66>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  g.mean()

          temperature  windspeed
city
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [ ]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
mumbai           4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
mumbai         4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

*concat*

In [ ]:
india_weather=pd.DataFrame({
    'city':['mumbai','delhi','bangalore'],
    'temperature':[35,40,30],
    'humidity':[60,80,20]
})
india_weather

        city  temperature  humidity
0     mumbai           35        60
1      delhi           40        80
2  bangalore           30        20

In [ ]:
us_weather=pd.DataFrame({
    'city':['newyork','chicago','dallas'],
    'temperature':[12,18,30],
    'humidity':[34,45,60]
})
us_weather

      city  temperature  humidity
0  newyork           12        34
1  chicago           18        45
2   dallas           30        60

In [ ]:
df = pd.concat([india_weather,us_weather])
df
#it is doing union but index is not continous

        city  temperature  humidity
0     mumbai           35        60
1      delhi           40        80
2  bangalore           30        20
0    newyork           12        34
1    chicago           18        45
2     dallas           30        60

In [ ]:
df = pd.concat([india_weather,us_weather],ignore_index=True)
df

        city  temperature  humidity
0     mumbai           35        60
1      delhi           40        80
2  bangalore           30        20
3    newyork           12        34
4    chicago           18        45
5     dallas           30        60

In [ ]:
#now i want each dataframe in group
df = pd.concat([india_weather,us_weather],keys=['india','usa'])
df

              city  temperature  humidity
india 0     mumbai           35        60
      1      delhi           40        80
      2  bangalore           30        20
usa   0    newyork           12        34
      1    chicago           18        45
      2     dallas           30        60

In [ ]:
df.loc['india']

        city  temperature  humidity
0     mumbai           35        60
1      delhi           40        80
2  bangalore           30        20

In [ ]:
df.loc['usa']

      city  temperature  humidity
0  newyork           12        34
1  chicago           18        45
2   dallas           30        60

In [ ]:
temperature_df=pd.DataFrame({
    'city':['mumbai','delhi','bangalore'],
    'temperature':[35,40,30]})
temperature_df

        city  temperature
0     mumbai           35
1      delhi           40
2  bangalore           30

In [ ]:
windspeed_df=pd.DataFrame({
    'city':['mumbai','delhi','bangalore'],
    'temperature':[12,20,30]})
windspeed_df

        city  temperature
0     mumbai           12
1      delhi           20
2  bangalore           30

In [ ]:
df = pd.concat([temperature_df,windspeed_df])
df

        city  temperature
0     mumbai           35
1      delhi           40
2  bangalore           30
0     mumbai           12
1      delhi           20
2  bangalore           30

In [ ]:
# it is just appending, we need windspped as additional column
df = pd.concat([temperature_df,windspeed_df],axis=1)
df

        city  temperature       city  temperature
0     mumbai           35     mumbai           12
1      delhi           40      delhi           20
2  bangalore           30  bangalore           30

In [ ]:
#here my dataframe are in order, what if my dataframes are not in order
windspeed_df=pd.DataFrame({
    'city':['mumbai','bangalore','delhi'],
    'temperature':[12,20,30]})
windspeed_df

        city  temperature
0     mumbai           12
1  bangalore           20
2      delhi           30

In [ ]:
df = pd.concat([temperature_df,windspeed_df],axis=1)
df
# see the cities are not matching after concating(so we need add index manually)

        city  temperature       city  temperature
0     mumbai           35     mumbai           12
1      delhi           40  bangalore           20
2  bangalore           30      delhi           30

In [ ]:
temperature_df=pd.DataFrame({
    'city':['mumbai','delhi','bangalore'],
    'temperature':[35,40,30]},index=[0,1,2])
temperature_df

        city  temperature
0     mumbai           35
1      delhi           40
2  bangalore           30

In [ ]:
windspeed_df=pd.DataFrame({
    'city':['mumbai','bangalore','delhi'],
    'temperature':[12,20,30]},index=[0,2,1])
windspeed_df
#but it is not advisable,to do this in better way we have merge in pandas

        city  temperature
0     mumbai           12
2  bangalore           20
1      delhi           30

In [ ]:
df = pd.concat([temperature_df,windspeed_df],axis=1)
df

        city  temperature       city  temperature
0     mumbai           35     mumbai           12
1      delhi           40      delhi           30
2  bangalore           30  bangalore           20

In [ ]:
df1=pd.DataFrame({
    'city':['mumbai','delhi','bangalore'],
    'temperature':[35,40,30]})
df1

        city  temperature
0     mumbai           35
1      delhi           40
2  bangalore           30

In [ ]:
df2=pd.DataFrame({
    'city':['mumbai','bangalore','delhi'],
    'windspeed':[12,20,30]})
df2

        city  windspeed
0     mumbai         12
1  bangalore         20
2      delhi         30

In [ ]:
df3 = pd.merge(df1,df2,on='city')
df3

        city  temperature  windspeed
0     mumbai           35         12
1      delhi           40         30
2  bangalore           30         20

In [ ]:
#what if i have additional values/columns
df1=pd.DataFrame({
    'city':['mumbai','delhi','bangalore','hyderabad'],
    'temperature':[35,40,30,38]})
df1

        city  temperature
0     mumbai           35
1      delhi           40
2  bangalore           30
3  hyderabad           38

In [ ]:
df2=pd.DataFrame({
    'city':['mumbai','bangalore','delhi','pune','kolkata'],
    'windspeed':[12,20,30,24,43]})
df2

        city  windspeed
0     mumbai         12
1  bangalore         20
2      delhi         30
3       pune         24
4    kolkata         43

In [ ]:
df3 = pd.merge(df1,df2,on='city')
df3
# by default it will do inner join

        city  temperature  windspeed
0     mumbai           35         12
1      delhi           40         30
2  bangalore           30         20

In [ ]:
df3 = pd.merge(df1,df2,on='city',how='inner')
df3

        city  temperature  windspeed
0     mumbai           35         12
1      delhi           40         30
2  bangalore           30         20

In [ ]:
df3 = pd.merge(df1,df2,on='city',how='left')
df3

        city  temperature  windspeed
0     mumbai           35       12.0
1      delhi           40       30.0
2  bangalore           30       20.0
3  hyderabad           38        NaN

In [ ]:
df3 = pd.merge(df1,df2,on='city',how='right')
df3

        city  temperature  windspeed
0     mumbai         35.0         12
1  bangalore         30.0         20
2      delhi         40.0         30
3       pune          NaN         24
4    kolkata          NaN         43

In [ ]:
df3 = pd.merge(df1,df2,on='city',how='outer')
df3

        city  temperature  windspeed
0     mumbai         35.0       12.0
1      delhi         40.0       30.0
2  bangalore         30.0       20.0
3  hyderabad         38.0        NaN
4       pune          NaN       24.0
5    kolkata          NaN       43.0

In [ ]:
#what if my dataframe has common columns
df1=pd.DataFrame({
    'city':['mumbai','delhi','bangalore'],
    'temperature':[35,40,30],
    'humidity':[60,80,20]
})
df1

        city  temperature  humidity
0     mumbai           35        60
1      delhi           40        80
2  bangalore           30        20

In [ ]:
df2=pd.DataFrame({
    'city':['newyork','chicago','dallas'],
    'temperature':[12,13,14],
    'humidity':[20,30,40]
})
df2

      city  temperature  humidity
0  newyork           12        20
1  chicago           13        30
2   dallas           14        40

In [ ]:
df3 = pd.merge(df1,df2,on='city')
df3

Empty DataFrame
Columns: [city, temperature_x, humidity_x, temperature_y, humidity_y]
Index: []

In [ ]:
df3 = pd.merge(df1,df2,on='city',how='outer')
df3

        city  temperature_x  humidity_x  temperature_y  humidity_y
0     mumbai           35.0        60.0            NaN         NaN
1      delhi           40.0        80.0            NaN         NaN
2  bangalore           30.0        20.0            NaN         NaN
3    newyork            NaN         NaN           12.0        20.0
4    chicago            NaN         NaN           13.0        30.0
5     dallas            NaN         NaN           14.0        40.0

In [ ]:
#And if i want to know from which df my valu is derived we have option indicator
df3 = pd.merge(df1,df2,on='city',how='outer',indicator=True)
df3

        city  temperature_x  humidity_x  temperature_y  humidity_y      _merge
0     mumbai           35.0        60.0            NaN         NaN   left_only
1      delhi           40.0        80.0            NaN         NaN   left_only
2  bangalore           30.0        20.0            NaN         NaN   left_only
3    newyork            NaN         NaN           12.0        20.0  right_only
4    chicago            NaN         NaN           13.0        30.0  right_only
5     dallas            NaN         NaN           14.0        40.0  right_only

In [ ]:
#Anf if i want my own suffixes instead of x,y i can mention in suffixes
df3 = pd.merge(df1,df2,on='city',how='outer',indicator=True,suffixes=['_left','_right'])
df3

,city,temperature_left,humidity_left,temperature_right,humidity_right,_merge
0,mumbai,35.0,60.0,NaN,NaN,left_only
1,delhi,40.0,80.0,NaN,NaN,left_only
2,bangalore,30.0,20.0,NaN,NaN,left_only
3,newyork,NaN,NaN,12.0,20.0,right_only
4,chicago,NaN,NaN,13.0,30.0,right_only
5,dallas,NaN,NaN,14.0,40.0,right_only

**pivot and pivot_table**

In [ ]:
df = pd.read_csv('weather.csv')
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [ ]:
df.pivot(index='city',columns='date')

         temperature                   humidity
date        5/1/2017 5/2/2017 5/3/2017 5/1/2017 5/2/2017 5/3/2017
city
beijing           80       77       79       26       30       35
mumbai            75       78       82       80       83       85
new york          65       66       68       56       58       60

In [ ]:
#if i want only one value
df.pivot(index='city',columns='date',values='temperature')

date      5/1/2017  5/2/2017  5/3/2017
city
beijing         80        77        79
mumbai          75        78        82
new york        65        66        68

In [ ]:
df = pd.read_csv('weather2.csv')
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [ ]:
df.pivot_table(index='city',columns='date')

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

In [ ]:
#for pivot_table by default aggfunc is mean(avg)
#if we want to change we can change
df.pivot_table(index='city',columns='date',aggfunc='sum')

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai        163      111         153      162
new york      110      122         126      142

In [ ]:
df.pivot_table(index='city',columns='date',aggfunc='count')

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai          2        2           2        2
new york        2        2           2        2

In [ ]:
pip install PyMySQL

Collecting PyMySQL
  Downloading PyMySQL-1.1.0-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.2 MB/s eta 0:00:00
Installing collected packages: PyMySQL
Successfully installed PyMySQL-1.1.0

In [ ]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (2.0.18)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (4.7.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (2.0.2)