<a href="https://colab.research.google.com/github/venkatesh1992/Practise/blob/mybranch/pandas_series_advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

##Reading files
* we will read csv files using read_csv() method

In [ ]:
csv_read = pd.read_csv('drinks.csv')

FileNotFoundError: ignored

In [ ]:
csv_read

In [ ]:
csv_read.head()

In [ ]:
csv_read.tail()

In [ ]:
#either we can download the file or we can provide any url path
# which can be anything i.e adls path/s3 path/ or any valid url
#eg: https://andybek.com/pandas-drinks

In [ ]:
pd.read_csv('https://andybek.com/pandas-drinks')

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,NaN,NaN,NaN,NaN
1,Albania,89.0,132.0,54.0,4.9
2,Algeria,25.0,NaN,14.0,0.7
3,Andorra,245.0,138.0,312.0,12.4
4,Angola,217.0,57.0,45.0,5.9
...,...,...,...,...,...
188,Venezuela,333.0,1.0,3.0,7.7
189,Vietnam,111.0,2.0,1.0,2.0
190,Yemen,6.0,NaN,NaN,0.1
191,Zambia,32.0,19.0,4.0,2.5
192,Zimbabwe,64.0,18.0,4.0,4.7

In [ ]:
# we can select required columns while reading file it self
pd.read_csv('https://andybek.com/pandas-drinks',usecols=['country','wine_servings'])

         country  wine_servings
0    Afghanistan            NaN
1        Albania           54.0
2        Algeria           14.0
3        Andorra          312.0
4         Angola           45.0
..           ...            ...
188    Venezuela            3.0
189      Vietnam            1.0
190        Yemen            NaN
191       Zambia            4.0
192     Zimbabwe            4.0

[193 rows x 2 columns]

In [ ]:
#now we will make country as index and wine servings as data
pd.read_csv('https://andybek.com/pandas-drinks',usecols=['country','wine_servings'],index_col='country')

             wine_servings
country
Afghanistan            NaN
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0
...                    ...
Venezuela              3.0
Vietnam                1.0
Yemen                  NaN
Zambia                 4.0
Zimbabwe               4.0

[193 rows x 1 columns]

In [ ]:
#even though we have single sequenceof values,it is not a series, still it is in dataframe only
# by default read_csv will return dataframe
drink_servings = pd.read_csv('https://andybek.com/pandas-drinks',usecols=['country','wine_servings'],index_col='country')

In [ ]:
drink_servings

             wine_servings
country
Afghanistan            NaN
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0
...                    ...
Venezuela              3.0
Vietnam                1.0
Yemen                  NaN
Zambia                 4.0
Zimbabwe               4.0

[193 rows x 1 columns]

In [ ]:
type(drink_servings)

pandas.core.frame.DataFrame

In [ ]:
#if we have only one column in dataframe we can convert it to series by using squeeze method
drink_servings = pd.read_csv('https://andybek.com/pandas-drinks',usecols=['country','wine_servings'],index_col='country',squeeze=True)

<ipython-input-64-66ab2e3df6e4>:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  drink_servings = pd.read_csv('https://andybek.com/pandas-drinks',usecols=['country','wine_servings'],index_col='country',squeeze=True)

In [ ]:
drink_servings

country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            NaN
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [ ]:
type(drink_servings)

pandas.core.series.Series

we will see some methods
* **size** : will return the count(number of records)
* **shape** : will give count in tuple(in dataframe it will give row count and clumns count), in series we have only one dimensional so it is giving record count only
* **len** : will give count of records only

In [ ]:
drink_servings.size

193

In [ ]:
drink_servings.values

array([ nan,  54.,  14., 312.,  45.,  45., 221.,  11., 212., 191.,   5.,
        51.,   7.,  nan,  36.,  42., 212.,   8.,  13.,  nan,   8.,   8.,
        35.,  16.,   1.,  94.,   7.,  nan,   7.,  16.,   1.,   4.,   1.,
         1.,   1., 172.,   8.,   3.,   1.,   9.,  74.,  11., 254.,   5.,
       113., 134.,  nan,   1., 278.,   3.,  26.,   9.,   3.,   1.,   2.,
       233.,  nan,  59.,  nan,   1.,  97.,  37.,  59.,   1., 149., 175.,
         1., 218.,  28.,   2.,   2.,  21.,   1.,   1.,   2., 185.,  78.,
        nan,  nan,  nan,  nan, 165.,   9., 237.,   9.,  16.,   1.,  12.,
         2.,   1.,  nan,   6., 123.,  62.,  31.,  nan,   2.,  nan,  56.,
       271.,   4.,   1.,  nan,  nan,   1.,  12.,  nan,  nan,  18.,   5.,
        18.,  nan,   8., 128.,   1.,   5.,  nan,   1.,   8.,  nan,  19.,
       175.,   1.,   1.,   2.,   7., 129.,   1.,  nan,  23.,  18.,   1.,
        74.,  21.,   1.,  56., 339.,   7.,   9.,  18., 167.,  73.,  nan,
        32.,  71.,  11.,  24.,  nan,  14.,  nan,   7., 127.,  51.,   2.,
        11., 116., 276.,   1.,  nan,  81., 112.,  nan,  nan,   7.,   2.,
       186.,  28.,  16.,  nan,   1.,  86.,   4.,  19.,   5.,   7.,   2.,
         7.,  32.,   9.,  nan,  45.,   5., 195.,   1.,  84.,  22.,   8.,
        11.,   3.,   1.,  nan,   4.,   4.])

In [ ]:
drink_servings.index

Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua & Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
       ...
       'Tanzania', 'USA', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela',
       'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='object', name='country', length=193)

In [ ]:
drink_servings.values.size

193

In [ ]:
drink_servings.values.size == drink_servings.index.size

True

In [ ]:
drink_servings.shape

(193,)

In [ ]:
len(drink_servings)

193

### unique values and monotonicity

In [ ]:
drink_servings.is_unique

False

In [ ]:
drink_servings.head()

country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
Name: wine_servings, dtype: float64

In [ ]:
drink_servings.head().is_unique

True

In [ ]:
# to get how many unique values we can use nunique method
drink_servings.nunique()

71

In [ ]:
# nunique won't count NaN's(by default)
drink_servings.nunique(dropna=False)

72

In [ ]:
pd.Series([1,2,3]).is_monotonic

<ipython-input-79-acb12a3a9c44>:1: FutureWarning: is_monotonic is deprecated and will be removed in a future version. Use is_monotonic_increasing instead.
  pd.Series([1,2,3]).is_monotonic

True

In [ ]:
# is_monotonic and is_monotonic_increasing both are same
pd.Series([1,2,3]).is_monotonic_increasing

True

In [ ]:
pd.Series([1,2,3,3,3]).is_monotonic_increasing

True

In [ ]:
pd.Series([1,2,3,4,5]).is_monotonic_increasing

True

In [ ]:
pd.Series([1,2,3,4,5,78,97,102]).is_monotonic_increasing

True

In [ ]:
pd.Series([1,2,3,4,5,78,97,102,55]).is_monotonic_increasing

False

In [ ]:
pd.Series(reversed([1,2,3,4,5,78,97,102])).is_monotonic_increasing

False

In [ ]:
pd.Series(reversed([1,2,3,4,5,78,97,102])).is_monotonic_decreasing

True

In [ ]:
#count method ignore nulls
drink_servings.count()

162

In [ ]:
drink_servings.size

193

In [ ]:
#to check if na are present or not we have hasnans methos
drink_servings.hasnans

True

In [ ]:
# how to get count of nulls
drink_servings.isnull()

country
Afghanistan     True
Albania        False
Algeria        False
Andorra        False
Angola         False
               ...
Venezuela      False
Vietnam        False
Yemen           True
Zambia         False
Zimbabwe       False
Name: wine_servings, Length: 193, dtype: bool

In [ ]:
drink_servings[drink_servings.isnull()]

country
Afghanistan        NaN
Bangladesh         NaN
Bhutan             NaN
Burundi            NaN
North Korea        NaN
Eritrea            NaN
Ethiopia           NaN
India              NaN
Indonesia          NaN
Iran               NaN
Iraq               NaN
Kuwait             NaN
Lesotho            NaN
Libya              NaN
Malaysia           NaN
Maldives           NaN
Marshall Islands   NaN
Mauritania         NaN
Monaco             NaN
Myanmar            NaN
Nepal              NaN
Pakistan           NaN
Rwanda             NaN
San Marino         NaN
Saudi Arabia       NaN
Somalia            NaN
Sri Lanka          NaN
Sudan              NaN
Tajikistan         NaN
Uganda             NaN
Yemen              NaN
Name: wine_servings, dtype: float64

In [ ]:
list(drink_servings[drink_servings.isnull()].index)

['Afghanistan',
 'Bangladesh',
 'Bhutan',
 'Burundi',
 'North Korea',
 'Eritrea',
 'Ethiopia',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Kuwait',
 'Lesotho',
 'Libya',
 'Malaysia',
 'Maldives',
 'Marshall Islands',
 'Mauritania',
 'Monaco',
 'Myanmar',
 'Nepal',
 'Pakistan',
 'Rwanda',
 'San Marino',
 'Saudi Arabia',
 'Somalia',
 'Sri Lanka',
 'Sudan',
 'Tajikistan',
 'Uganda',
 'Yemen']

In [ ]:
len(list(drink_servings[drink_servings.isnull()].index))

31

In [ ]:
# the above is some what lengthy process,is there any  alternate
drink_servings.isnull().sum()

31

In [ ]:
# isnull and isna both are same(aliases)
drink_servings.isna().sum()

31

In [ ]:
# in python True is considered as 1 and Flase to 0
sum([True,True,False])

2

In summary
* **size**  will give all the records count
* **count** will give not null records count
* **isnull().sum()** will give null records count

In [ ]:
# we have notnull and notna functions also
drink_servings.notnull()

country
Afghanistan    False
Albania         True
Algeria         True
Andorra         True
Angola          True
               ...
Venezuela       True
Vietnam         True
Yemen          False
Zambia          True
Zimbabwe        True
Name: wine_servings, Length: 193, dtype: bool

In [ ]:
drink_servings.notnull().sum()

162

In [ ]:
drink_servings.notna

<bound method Series.notna of country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            NaN
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64>

In [ ]:
drink_servings.notna().sum()

162

In [ ]:
# in python bools are inherited from ints, so True is considered as 1 and False is considered as 0
True + 19

20

In [ ]:
True + True -False +True*3

5

In [ ]:
5/False

ZeroDivisionError: ignored

In [ ]:
type(True)

In [ ]:
#and we can check from where it is inherited by using method resolution oreder(mro)
bool.__mro__

(bool, int, object)

### dropping and filling nulls
* dropna
* fillna

In [ ]:
drink_servings.dropna()

country
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0
Antigua & Barbuda     45.0
                     ...
Vanuatu               11.0
Venezuela              3.0
Vietnam                1.0
Zambia                 4.0
Zimbabwe               4.0
Name: wine_servings, Length: 162, dtype: float64

In [ ]:
drink_servings

country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            NaN
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [ ]:
#if we observe above,our original series doesn't change
# dropna will create a new copy out of original
# if we want to modify original series, we have two ways 1.reassignment and second one is inplace=True

In [ ]:
#drink_servings = drink_servings.dropna()

In [ ]:
#drink_servings

In [ ]:
drink_servings

country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            NaN
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [ ]:
#drink_servings.dropna(inplace=True)

In [ ]:
#drink_servings

country
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0
Antigua & Barbuda     45.0
                     ...
Vanuatu               11.0
Venezuela              3.0
Vietnam                1.0
Zambia                 4.0
Zimbabwe               4.0
Name: wine_servings, Length: 162, dtype: float64

In [ ]:
drink_servings = pd.read_csv('https://andybek.com/pandas-drinks',usecols=['country','wine_servings'],index_col='country',squeeze=True)

<ipython-input-115-155b7dac99ff>:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  drink_servings = pd.read_csv('https://andybek.com/pandas-drinks',usecols=['country','wine_servings'],index_col='country',squeeze=True)

In [ ]:
drink_servings

country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            NaN
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [ ]:
drink_servings.fillna(0)

country
Afghanistan      0.0
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            0.0
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [ ]:
drink_servings

country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            NaN
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [ ]:
drink_servings.fillna(0,inplace=True)

In [ ]:
drink_servings

country
Afghanistan      0.0
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            0.0
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [ ]:
drink_servings = pd.read_csv('https://andybek.com/pandas-drinks',usecols=['country','wine_servings'],index_col='country',squeeze=True)

<ipython-input-121-155b7dac99ff>:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  drink_servings = pd.read_csv('https://andybek.com/pandas-drinks',usecols=['country','wine_servings'],index_col='country',squeeze=True)